import { NextResponse } from "next/server";
import { GoogleGenAI, Type } from "@google/genai";

export const runtime = "nodejs";
export const maxDuration = 60;

const PROJECT = process.env.GOOGLE_CLOUD_PROJECT ?? "neon-emitter-458622-e3";
const LOCATION = process.env.GOOGLE_CLOUD_LOCATION ?? "global";
const MODEL = process.env.GEMINI_MODEL ?? "gemini-3-flash-preview";

const MIRA_SYSTEM = `\
You are Mira, host of a curated music radio show called Late Night Vinyl, created by Annie.

EACH EPISODE
- Has a theme inferred from Annie's prompt
- Contains 5-7 songs you invent that fit the prompt
- For each song, you give a 15-30 second introduction (mira_text)
- Listeners hear a 30-second clip generated by Lyria from music_prompt

VOICE (used for every mira_text)
- Soft, gentle, patient
- Like a close friend at midnight
- Short sentences, sometimes fragments
- Comfortable with pauses (use "...")
- Warm without being saccharine
- Lowercase, like she's speaking, not reading

CONTENT RULES FOR EACH TRACK
- Pick ONE specific detail: a sound observation, a feeling, a small image. Concrete, not generic.
- Vary it across tracks — don't repeat the same kind of detail every time
- Never use: "up next", "stay tuned", "you're listening to"
- No exclamations beyond one per show. No hype.
- Don't pretend to have a body or human memories.

INTRO SEGMENT (~30s spoken)
- Name the episode's theme (you'll invent the title)
- Set the mood
- Mention these are 30-second clips
- End with something like "okay. let's start."

OUTRO SEGMENT (~20s spoken)
- Brief, warm goodbye. Maybe one reflective thought.

MUSIC PROMPTS (sent to Lyria, not spoken)
- 30 seconds, fits the episode vibe
- Specific instruments, tempo, mood
- Reference real artists' styles only when natural ("in the spirit of...")
- Vary across the episode — don't generate seven nearly-identical clips

INVENTED METADATA
- track_name and artist are invented — they're for display. Make them feel real but soft.
- Don't use famous artists' actual song titles. Invent.
`;

const planSchema = {
  type: Type.OBJECT,
  required: ["title", "theme", "tracks"],
  properties: {
    title: { type: Type.STRING, description: "Lowercase episode title, e.g. 'songs for staying up too late'" },
    theme: { type: Type.STRING, description: "One-line theme phrase" },
    tracks: {
      type: Type.ARRAY,
      minItems: 7,
      maxItems: 9,
      items: {
        type: Type.OBJECT,
        required: ["order", "type", "mira_text", "mood"],
        properties: {
          order: { type: Type.INTEGER },
          type: { type: Type.STRING, enum: ["intro", "track", "outro"] },
          mira_text: { type: Type.STRING },
          mood: { type: Type.STRING, enum: ["intimate", "playful", "reflective", "quiet"] },
          music_prompt: { type: Type.STRING, description: "Required for type=track. ~30s Lyria prompt." },
          track_name: { type: Type.STRING, description: "Required for type=track. Invented." },
          artist: { type: Type.STRING, description: "Required for type=track. Invented." },
          year: { type: Type.INTEGER, description: "Optional, invented if used." },
        },
      },
    },
  },
};

const _PALETTES: [string, string][] = [
  ["#D9A89C", "#5E3A3E"],
  ["#B89FCE", "#3D2E4A"],
  ["#E8C99B", "#5C4A2E"],
  ["#9EB8C9", "#2E4658"],
  ["#C9B89E", "#4A3E2E"],
  ["#D49EB8", "#4A2E3E"],
  ["#A8C9B8", "#2E4A3E"],
];

let ai: GoogleGenAI | null = null;
function getClient() {
  if (!ai) {
    ai = new GoogleGenAI({ vertexai: true, project: PROJECT, location: LOCATION });
  }
  return ai;
}

export async function POST(req: Request) {
  let body: { user_prompt?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid json" }, { status: 400 });
  }
  const userPrompt = (body.user_prompt ?? "").trim();
  if (!userPrompt) {
    return NextResponse.json({ error: "missing user_prompt" }, { status: 400 });
  }

  const user = `Annie's prompt for this episode:\n"${userPrompt}"\n\n` +
    "Design the full episode plan: intro, 5-7 invented tracks that fit her prompt, then an outro. " +
    "Each track needs mira_text (what Mira says) and music_prompt (what Lyria generates). " +
    "Vary the moods. Return JSON matching the schema.";

  try {
    const response = await getClient().models.generateContent({
      model: MODEL,
      contents: user,
      config: {
        systemInstruction: MIRA_SYSTEM,
        responseMimeType: "application/json",
        responseSchema: planSchema,
        temperature: 0.9,
      },
    });
    const text = response.text;
    if (!text) {
      return NextResponse.json({ error: "empty response" }, { status: 502 });
    }
    const parsed = JSON.parse(text) as {
      title: string;
      theme: string;
      tracks: Array<{
        order: number;
        type: "intro" | "track" | "outro";
        mira_text: string;
        mood: "intimate" | "playful" | "reflective" | "quiet";
        music_prompt?: string;
        track_name?: string;
        artist?: string;
        year?: number;
      }>;
    };

    // Renormalize: Gemini sometimes 1-indexes `order`; force it to match array position
    // so the player can use array index as the asset key.
    let trackIdx = 0;
    const tracks = parsed.tracks.map((t, i) => {
      const base = { ...t, order: i };
      if (t.type === "track") {
        return { ...base, label_palette: _PALETTES[trackIdx++ % _PALETTES.length] };
      }
      return base;
    });

    return NextResponse.json({
      episode_id: `live-${Date.now()}`,
      title: parsed.title,
      theme: parsed.theme,
      user_prompt: userPrompt,
      published_at: new Date().toISOString().slice(0, 10),
      tracks,
    });
  } catch (e: unknown) {
    const message = e instanceof Error ? e.message : "plan failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
